---
name: "test_matrix"

on:  # yamllint disable-line rule:truthy
  pull_request:
    branches: main
  push:
    branches-ignore:
      - '*_test'
      - '*_dev'
      - '*_cloud'
    paths-ignore:
      - '**.md'
      - 'LICENSE'

jobs:
  tests:
    name: Python ${{ matrix.python-version }} | Clickhouse ${{ matrix.clickhouse-version}} | Ubuntu
    runs-on: ubuntu-latest
    env:
      TEST_SETTINGS_FILE: latest

    strategy:
      matrix:
        python-version:
          - '3.10'
          - '3.11'
          - '3.12'
          - '3.13'
        clickhouse-version:
          - '25.1'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run ClickHouse Cluster Containers
        env:
          PROJECT_ROOT: ${{ github.workspace }}/tests/integration
        run: REPLICA_NUM=1 docker compose -f ${{ github.workspace }}/tests/integration/docker-compose.yml up -d

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install requirements
        run: pip3 install -r dev_requirements.txt

      - name: Run HTTP tests
        env:
          DBT_CH_TEST_CLUSTER: test_shard
        run: |
          PYTHONPATH="${PYTHONPATH}:dbt"
          pytest tests

      - name: Run Native tests
        env:
          DBT_CH_TEST_PORT: 9000
          DBT_CH_TEST_CLUSTER: test_shard
        run: |
          PYTHONPATH="${PYTHONPATH}:dbt"
          pytest tests
